FROM python:3.8

WORKDIR /usr/src/app
COPY . .
RUN pip install --no-cache-dir .
RUN pip install --no-cache-dir pymysql psycopg2 cryptography 'celery[redis]' redis
ENV PEEWEE_PROTO mysql
ENV PEEWEE_USER notifications
ENV PEEWEE_PASS notifications
ENV PEEWEE_PORT 3306
ENV PEEWEE_ADDR 127.0.0.1
ENV PEEWEE_DATABASE pacifica_notifications
ENTRYPOINT [ "/bin/bash", "/usr/src/app/entrypoint-celery.sh" ]
