version: '3.3'
volumes:
  ingestdata:
services:
  ingestfrontend:
    image: pacifica/ingest-frontend
    links:
    - uniqueid
    - metadataserver
    - archiveinterface
    - policyserver
    - ingestrabbit
    - ingestmysql
    ports:
    - 8066:8066
    volumes:
    - ingestdata:/srv
    environment:
      VOLUME_PATH: /srv
      PEEWEE_ADDR: ingestmysql
      BROKER_URL: pyamqp://ingestrabbit
      UNIQUEID_URL: http://uniqueid:8051
      POLICY_INGEST_URL: http://policyserver:8181/ingest
      METADATA_INGEST_URL: http://metadataserver:8121/ingest
      ARCHIVEINTERFACE_URL: http://archiveinterface:8080

  ingestbackend:
    image: pacifica/ingest-backend
    links:
    - uniqueid
    - metadataserver
    - archiveinterface
    - policyserver
    - ingestrabbit
    - ingestmysql
    volumes:
    - ingestdata:/srv
    environment:
      VOLUME_PATH: /srv
      PEEWEE_ADDR: ingestmysql
      BROKER_URL: pyamqp://ingestrabbit
      UNIQUEID_URL: http://uniqueid:8051
      POLICY_INGEST_URL: http://policyserver:8181/ingest
      METADATA_INGEST_URL: http://metadataserver:8121/ingest
      ARCHIVEINTERFACE_URL: http://archiveinterface:8080

  ingestmysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacifica_ingest
      MYSQL_USER: ingest
      MYSQL_PASSWORD: ingest

  ingestrabbit:
    image: rabbitmq

  uniqueidmysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacifica_uniqueid
      MYSQL_USER: uniqueid
      MYSQL_PASSWORD: uniqueid

  uniqueid:
    image: pacifica/uniqueid
    links:
    - uniqueidmysql:mysql
    environment:
      PEEWEE_ADDR: mysql

  archiveinterface:
    image: pacifica/archiveinterface

  policyserver:
    image: pacifica/policy
    ports:
    - 8181:8181
    links:
    - metadataserver:metadata
    environment:
      METADATA_URL: http://metadata:8121
      STATUS_URL: http://metadata:8121/groups

  metadatadb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: metadata
      POSTGRES_DB: pacifica_metadata
      POSTGRES_USER: pacifica

  metadataserver:
    image: pacifica/metadata
    links:
    - metadatadb
    environment:
      PEEWEE_DATABASE: pacifica_metadata
      PEEWEE_USER: pacifica
      PEEWEE_ADDR: metadatadb
      PEEWEE_PORT: 5432
      PEEWEE_PROTO: postgres
      PEEWEE_PASS: metadata
      NOTIFICATIONS_URL: http://notifyfrontend:8070/receive
    ports:
      - 8121:8121

  notifyredis:
    image: redis
    ports:
      - 6379:6379

  notifydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: notifications
      POSTGRES_DB: pacifica_notifications
      POSTGRES_USER: notifications
    ports:
      - 5432:5432

  notifybackend:
    build:
      context: .
      dockerfile: Dockerfile.celery
    links:
    - notifyredis:redis
    - notifydb:pgsql
    environment:
      PEEWEE_ADDR: pgsql
      BROKER_URL: redis://redis:6379/0
      POLICY_URL: http://policyserver:8181

  notifyfrontend:
    build:
      context: .
      dockerfile: Dockerfile.uwsgi
    ports:
    - 8070:8070
    links:
    - notifyredis:redis
    - notifydb:pgsql
    environment:
      PEEWEE_ADDR: pgsql
      BROKER_URL: redis://redis:6379/0
      POLICY_URL: http://policyserver:8181
